Feature/pn 2440
pagopa/pn-logsaver-be pull request #8
Opened 2022-11-16 13:34 UTC by antoniopezzuto

2022-11-24 10:51 UTC, fdammassa requested changes
Ti ho lasciato dei commenti.

2022-11-24 13:05 UTC, antoniopezzuto commented on src/main/java/it/pagopa/pn/logsaver/config/LogSaverCfg.java
> +  @Value("${log-saver.export-max-file-size:5MB}")
Ok, la documentazione è stata aggiornata contestualmente

2022-11-24 13:09 UTC, antoniopezzuto commented on src/main/java/it/pagopa/pn/logsaver/client/safestorage/PnSafeStorageClientImpl.java
> +  private String uploadFile(Path filePath, ExportType exportType, Retention retention) {
Ok, ho cambiato il nome del public

2022-11-29 08:28 UTC, fdammassa approved these changes

2022-11-29 08:28 UTC, merged